CREATE TABLE "company" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "warehouse" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" int,
  "name" varchar
);

CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" int,
  "name" varchar,
  "sku" varchar,
  "price" decimal
);

CREATE TABLE "inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "warehouse_id" int,
  "quantity" int
);

CREATE TABLE "inventory_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventory_id" int,
  "change_quantity" int,
  "reason" varchar,
  "created_at" datetime
);

CREATE TABLE "supplier" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "purchase_order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" int,
  "warehouse_id" int,
  "created_at" datetime
);

CREATE TABLE "purchase_order_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_order_id" int,
  "product_id" int,
  "quantity" int
);

CREATE TABLE "customer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" int,
  "name" varchar
);

CREATE TABLE "sales_order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "warehouse_id" int,
  "created_at" datetime
);

CREATE TABLE "sales_order_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sales_order_id" int,
  "product_id" int,
  "quantity" int
);

CREATE TABLE "product_bundle" (
  "bundle_product_id" int,
  "component_product_id" int,
  "component_quantity" int
);

CREATE UNIQUE INDEX ON "product" ("company_id", "sku");

CREATE UNIQUE INDEX ON "inventory" ("product_id", "warehouse_id");

CREATE UNIQUE INDEX ON "product_bundle" ("bundle_product_id", "component_product_id");

ALTER TABLE "warehouse" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "product" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id");

ALTER TABLE "inventory_history" ADD FOREIGN KEY ("inventory_id") REFERENCES "inventory" ("id");

ALTER TABLE "purchase_order" ADD FOREIGN KEY ("supplier_id") REFERENCES "supplier" ("id");

ALTER TABLE "purchase_order" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id");

ALTER TABLE "purchase_order_item" ADD FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_order" ("id");

ALTER TABLE "purchase_order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "customer" ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "sales_order" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id");

ALTER TABLE "sales_order" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouse" ("id");

ALTER TABLE "sales_order_item" ADD FOREIGN KEY ("sales_order_id") REFERENCES "sales_order" ("id");

ALTER TABLE "sales_order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "product_bundle" ADD FOREIGN KEY ("bundle_product_id") REFERENCES "product" ("id");

ALTER TABLE "product_bundle" ADD FOREIGN KEY ("component_product_id") REFERENCES "product" ("id");
